-- ADDON:ImportAPI(API.X2Ability)
-- ADDON:ImportAPI(API.X2Achievement)
-- ADDON:ImportAPI(API.X2Action)
-- ADDON:ImportAPI(API.X2ArchePass)
-- ADDON:ImportAPI(API.X2Auction)
ADDON:ImportAPI(API.X2Bag)
ADDON:ImportAPI(API.X2Bank)
-- ADDON:ImportAPI(API.X2BattleField)
-- ADDON:ImportAPI(API.X2BlessUthstin)
-- ADDON:ImportAPI(API.X2Book)
-- ADDON:ImportAPI(API.X2BuffSkill)
-- ADDON:ImportAPI(API.X2Butler)
-- ADDON:ImportAPI(API.X2Camera)
-- ADDON:ImportAPI(API.X2Chat)
ADDON:ImportAPI(API.X2Coffer)
-- ADDON:ImportAPI(API.X2CombatResource)
-- ADDON:ImportAPI(API.X2Console)
-- ADDON:ImportAPI(API.X2Craft)
-- ADDON:ImportAPI(API.X2Cursor)
-- ADDON:ImportAPI(API.X2Customizer)
-- ADDON:ImportAPI(API.X2CustomizingUnit)
-- ADDON:ImportAPI(API.X2Debug)
-- ADDON:ImportAPI(API.X2Decal)
-- ADDON:ImportAPI(API.X2DialogManager)
-- ADDON:ImportAPI(API.X2Dominion)
-- ADDON:ImportAPI(API.X2Dyeing)
-- ADDON:ImportAPI(API.X2Equipment)
-- ADDON:ImportAPI(API.X2EquipSlotReinforce)
-- ADDON:ImportAPI(API.X2EventCenter)
-- ADDON:ImportAPI(API.X2Faction)
-- ADDON:ImportAPI(API.X2Family)
-- ADDON:ImportAPI(API.X2Friend)
-- ADDON:ImportAPI(API.X2GoodsMail)
-- ADDON:ImportAPI(API.X2GuildBank)
-- ADDON:ImportAPI(API.X2HeirSkill)
-- ADDON:ImportAPI(API.X2Helper)
-- ADDON:ImportAPI(API.X2Hero)
-- ADDON:ImportAPI(API.X2Hotkey)
-- ADDON:ImportAPI(API.X2House)
-- ADDON:ImportAPI(API.X2Indun)
-- ADDON:ImportAPI(API.X2InGameShop)
-- ADDON:ImportAPI(API.X2Input)
-- ADDON:ImportAPI(API.X2Interaction)
-- ADDON:ImportAPI(API.X2Item)
-- ADDON:ImportAPI(API.X2ItemEnchant)
-- ADDON:ImportAPI(API.X2ItemGacha)
-- ADDON:ImportAPI(API.X2ItemGuide)
-- ADDON:ImportAPI(API.X2ItemLookConverter)
ADDON:ImportAPI(API.X2Locale)
-- ADDON:ImportAPI(API.X2LoginCharacter)
-- ADDON:ImportAPI(API.X2Loot)
-- ADDON:ImportAPI(API.X2Mail)
-- ADDON:ImportAPI(API.X2Map)
-- ADDON:ImportAPI(API.X2Mate)
-- ADDON:ImportAPI(API.X2MiniScoreboard)
-- ADDON:ImportAPI(API.X2NameTag)
-- ADDON:ImportAPI(API.X2Nation)
-- ADDON:ImportAPI(API.X2OneAndOneChat)
-- ADDON:ImportAPI(API.X2Option)
-- ADDON:ImportAPI(API.X2Player)
-- ADDON:ImportAPI(API.X2PremiumService)
-- ADDON:ImportAPI(API.X2Quest)
-- ADDON:ImportAPI(API.X2Rank)
-- ADDON:ImportAPI(API.X2RenewItem)
-- ADDON:ImportAPI(API.X2Resident)
-- ADDON:ImportAPI(API.X2Roster)
-- ADDON:ImportAPI(API.X2Security)
-- ADDON:ImportAPI(API.X2SiegeWeapon)
-- ADDON:ImportAPI(API.X2Skill)
-- ADDON:ImportAPI(API.X2SkillAlert)
-- ADDON:ImportAPI(API.X2Sound)
-- ADDON:ImportAPI(API.X2Squad)
-- ADDON:ImportAPI(API.X2Store)
-- ADDON:ImportAPI(API.X2SurveyForm)
-- ADDON:ImportAPI(API.X2Team)
-- ADDON:ImportAPI(API.X2Time)
-- ADDON:ImportAPI(API.X2Trade)
-- ADDON:ImportAPI(API.X2Trial)
-- ADDON:ImportAPI(API.X2Tutorial)
-- ADDON:ImportAPI(API.X2Ucc)
-- ADDON:ImportAPI(API.X2Unit)
-- ADDON:ImportAPI(API.X2UserMusic)
-- ADDON:ImportAPI(API.X2Util)
-- ADDON:ImportAPI(API.X2Warp)
-- ADDON:ImportAPI(API.X2World)

-- ADDON:ImportObject(OBJECT.Avi)
ADDON:ImportObject(OBJECT.Button)
-- ADDON:ImportObject(OBJECT.ChatEdit)
-- ADDON:ImportObject(OBJECT.ChatMessage)
-- ADDON:ImportObject(OBJECT.ChatWindow)
ADDON:ImportObject(OBJECT.CheckButton)
-- ADDON:ImportObject(OBJECT.CircleDiagram)
-- ADDON:ImportObject(OBJECT.ColorDrawable)
-- ADDON:ImportObject(OBJECT.ColorPicker)
ADDON:ImportObject(OBJECT.Combobox)
-- ADDON:ImportObject(OBJECT.ComboListButton)
-- ADDON:ImportObject(OBJECT.CooldownButton)
-- ADDON:ImportObject(OBJECT.CooldownConstantButton)
-- ADDON:ImportObject(OBJECT.CooldownInventoryButton)
-- ADDON:ImportObject(OBJECT.DamageDisplay)
-- ADDON:ImportObject(OBJECT.Drawable)
-- ADDON:ImportObject(OBJECT.DynamicList)
-- ADDON:ImportObject(OBJECT.Editbox)
-- ADDON:ImportObject(OBJECT.EditboxMultiline)
-- ADDON:ImportObject(OBJECT.EffectDrawable)
ADDON:ImportObject(OBJECT.EmptyWidget)
-- ADDON:ImportObject(OBJECT.Folder)
ADDON:ImportObject(OBJECT.GameTooltip)
-- ADDON:ImportObject(OBJECT.Grid)
-- ADDON:ImportObject(OBJECT.IconDrawable)
ADDON:ImportObject(OBJECT.ImageDrawable)
-- ADDON:ImportObject(OBJECT.Label)
-- ADDON:ImportObject(OBJECT.Line)
ADDON:ImportObject(OBJECT.Listbox)
-- ADDON:ImportObject(OBJECT.ListCtrl)
-- ADDON:ImportObject(OBJECT.MegaphoneChatEdit)
-- ADDON:ImportObject(OBJECT.Message)
-- ADDON:ImportObject(OBJECT.ModelView)
ADDON:ImportObject(OBJECT.NinePartDrawable)
-- ADDON:ImportObject(OBJECT.Pageable)
-- ADDON:ImportObject(OBJECT.PaintColorPicker)
ADDON:ImportObject(OBJECT.RadioGroup)
-- ADDON:ImportObject(OBJECT.RoadMap)
-- ADDON:ImportObject(OBJECT.Root)
ADDON:ImportObject(OBJECT.Slider)
-- ADDON:ImportObject(OBJECT.SliderTab)
-- ADDON:ImportObject(OBJECT.Slot)
-- ADDON:ImportObject(OBJECT.StatusBar)
-- ADDON:ImportObject(OBJECT.Tab)
ADDON:ImportObject(OBJECT.Textbox)
-- ADDON:ImportObject(OBJECT.TextDrawable)
ADDON:ImportObject(OBJECT.TextStyle)
-- ADDON:ImportObject(OBJECT.TextureDrawable)
-- ADDON:ImportObject(OBJECT.ThreeColorDrawable)
-- ADDON:ImportObject(OBJECT.ThreePartDrawable)
-- ADDON:ImportObject(OBJECT.UnitframeTooltip)
-- ADDON:ImportObject(OBJECT.Webbrowser)
-- ADDON:ImportObject(OBJECT.Webview)
ADDON:ImportObject(OBJECT.Window)
-- ADDON:ImportObject(OBJECT.WorldMap)
ADDON:ImportObject(OBJECT.X2Editbox)
